baseURL = "/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "dopetrope"

[params]

[params.blog]
foldername = "blog"
title = "The Blog"
viewalltext = "View All"

[params.portfolio]
findoutmoretext = "Find out more"
foldername = "portfolio"
title = "My Portfolio"

[params.settings]
googleanalytics = "UA-000000000-1"